### ISSUE TITLE
funnel task create request is cacheable?

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#69]
I'm not sure why, but `funnel task create` is behaving differently than the equivalent curl command when run against GCE.

With some debugging to dump the HTTP response body:
```
./bin/funnel task create --server http://35.185.217.211/ examples/hello-world.json
DEBU tes        BODY                            unknown={"jobs":[{"jobID":"b3mkkmnntf6gd19v3t10","state":"Initializing","task":{"name":"Hello world","description":"Simple Echo Command"}}]}
```

The body contains a cached response from a previous request to ListTasks. GCE is caching http responses. It is strange that GCE is caching POST responses, but curl is doing something that prevents this.

**Comment by buchanae** [comment]
Python (py_tes.py) behaves the same way, so not sure this is a funnel bug or a GCE quirk

**Comment by buchanae** [comment]
Verifying that this is not specific to port 80, it also happens on port 8000
```
./bin/funnel task create --server http://35.185.217.211:8000/ examples/hello-world.json
DEBU tes        BODY                            unknown={"jobs":[{"jobID":"b3mkkmnntf6gd19v3t10","state":"Complete","task":{"name":"Hello world","description":"Simple Echo Command"}},{"jobID":"b3ml0anntf6gd19v3t1g","state":"Complete","task":{"name":"Hello world","description":"Simple Echo Command"}},{"jobID":"b3ml0bnntf6gd19v3t20","state":"Complete","task":{"name":"Hello world","description":"Simple Echo Command"}},{"jobID":"b3ml51fntf6gd19v3t2g","state":"Complete","task":{"name":"Hello world","description":"Simple Echo Command"}}]}
```

**Comment by buchanae** [comment]
The problem is that I had a trailing slash on my server, which results in a server URL `http://35.185.217.211//v1/jobs` (double slash) which then results in a 301 redirect, which screws up POST requests.

```
RJHB552 funnel (gce-deploy-cleanup)
python python/py_tes.py --server http://35.185.217.211/ examples/hello-world.json
<urllib2.Request instance at 0x109c5e170>
send: 'POST //v1/jobs HTTP/1.1\r\nAccept-Encoding: identity\r\nContent-Length: 193\r\nHost: 35.185.217.211\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: close\r\nUser-Agent: Python-urllib/2.7\r\n\r\n{"projectId": "Funnel", "docker": [{"cmd": ["echo", "hello", "world"], "imageName": "ubuntu", "stdout": "stdout"}], "name": "Hello world", "resources": {}, "description": "Simple Echo Command"}'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Location: /v1/jobs
header: Date: Tue, 11 Apr 2017 22:42:10 GMT
header: Content-Length: 0
header: Content-Type: text/plain; charset=utf-8
header: Age: 0
header: Connection: close
header: Via: 1.1 bladex.ohsu.edu
send: 'GET /v1/jobs HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: 35.185.217.211\r\nConnection: close\r\nUser-Agent: Python-urllib/2.7\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: application/json
header: Date: Tue, 11 Apr 2017 22:05:45 GMT
header: Content-Length: 482
header: Age: 2185
header: Connection: close
header: Via: 1.1 bladex.ohsu.edu
{u'jobs': [{u'state': u'Complete', u'task': {u'name': u'Hello world', u'description': u'Simple Echo Command'}, u'jobID': u'b3mkkmnntf6gd19v3t10'}, {u'state': u'Complete', u'task': {u'name': u'Hello world', u'description': u'Simple Echo Command'}, u'jobID': u'b3ml0anntf6gd19v3t1g'}, {u'state': u'Complete', u'task': {u'name': u'Hello world', u'description': u'Simple Echo Command'}, u'jobID': u'b3ml0bnntf6gd19v3t20'}, {u'state': u'Complete', u'task': {u'name': u'Hello world', u'description': u'Simple Echo Command'}, u'jobID': u'b3ml51fntf6gd19v3t2g'}]}
Traceback (most recent call last):
  File "python/py_tes.py", line 119, in <module>
    job_id = c.submit(t)
  File "python/py_tes.py", line 93, in submit
    job_id = data['value']
KeyError: 'value'
RJHB552 funnel (gce-deploy-cleanup)
python python/py_tes.py --server http://35.185.217.211 examples/hello-world.json
<urllib2.Request instance at 0x10941b170>
send: 'POST /v1/jobs HTTP/1.1\r\nAccept-Encoding: identity\r\nContent-Length: 193\r\nHost: 35.185.217.211\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: close\r\nUser-Agent: Python-urllib/2.7\r\n\r\n{"projectId": "Funnel", "docker": [{"cmd": ["echo", "hello", "world"], "imageName": "ubuntu", "stdout": "stdout"}], "name": "Hello world", "resources": {}, "description": "Simple Echo Command"}'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: application/json
header: Date: Tue, 11 Apr 2017 22:48:10 GMT
header: Content-Length: 32
header: Age: 0
header: Connection: close
header: Via: 1.1 bladex.ohsu.edu
{u'value': u'b3mlqanntf6gd19v3t30'}
```

**Comment by buchanae** [comment]
There's also an issue with the List endpoint, which GCE is currently caching but shouldn't be by default.

**Comment by adamstruck** [comment]
@buchanae this was fixed in #71 right?

**Comment by buchanae** [comment]
There is still an issue with the `funnel task list` (and probably related) commands not handling a trailing slash properly, which I'll fix this morning

**Comment by buchanae** [comment]
#79 makes some improvements, but I'm still seeing some strange behavior. Still working on this.

**Comment by buchanae** [comment]
Fixed by #86
